service: tools-clifflu-net

provider:
  name: aws
  deploymentBucket: net.clifflu.sls-deploy.${self:provider.region}
  runtime: nodejs6.10
  stage: prod
  region: us-west-2
  memorySize: 256
  timeout: 5
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ec2:describeImages
        - ec2:describeRegions
      Resource: "*"

functions:
  ami:
    handler: handler.ami
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  ip:
    handler: handler.ip
    events:
      - http:
          path: ip
          method: get
